fixed tailwind
anyuka007/Nestory pull request #2
Opened 2024-10-21 15:54 UTC by LuJian2024

we can now use TailwindCss

2024-10-21 16:29 UTC, anyuka007 requested changes

2024-10-21 16:29 UTC, anyuka007 commented on backend/lib/db.js
> +import colors from "colors";
das braucht man hier nicht, oder?  das functioniert ohne das, mann braucht nur npm i machen, colors dependency ist schon drinnen

2024-10-22 08:23 UTC, LuJian2024 commented on backend/lib/db.js
> +import colors from "colors";
alles ok

2024-10-22 08:24 UTC, anyuka007 approved these changes

2024-10-22 08:24 UTC, merged